name: "Goodreads Profile Workflow"
author: "Simon Wicki"
description: "Show what you're currently reading and recently read on your GitHub profile readme"
inputs:
  goodreads_user_id:
    description: "Your goodreads user id you want to have the lists fetched from (go to 'My Books' to see it in the URL)"
    required: true
  shelf:
    default: "currently-reading"
    required: false
  max_books_count:
    default: "10"
    required: false
  readme_file_path:
    default: "./README.md"
    required: false
  output_only:
    default: "false"
    required: false
  comment_tag_name:
    default: "GOODREADS-LIST"
    required: false
  template:
    default: "- [$title]($url) by $author (⭐️$average_rating)"
    required: false
  sort_by_fields:
    default: ">pubDate"
    required: false
outputs:
  books:
    description: "stringified JSON of fetched books"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "book"
  color: "gray-dark"